FROM debian:sid-slim@sha256:e3033e137f0c07eb10c565a699c470906b4b8300d2521ba85069255ab070bebf

RUN echo "deb http://deb.debian.org/debian/ sid main" >>  /etc/apt/sources.list && \
  echo "deb-src http://deb.debian.org/debian/ sid main" >>  /etc/apt/sources.list && \
  apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && \
  apt-get install -y python3 python3-pip python3-venv libapache2-mod-wsgi-py3 libmariadb-dev gcc pkg-config\
  apache2 apache2-data apache2-bin apache2-utils --allow-downgrades && \
  apt-get autoremove -y && apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
  cp /usr/bin/dpkg /tmp/dpkg && \
  /tmp/dpkg -P --force-remove-essential --force-depends apt dpkg && \
  rm -rf \
  /tmp/dpkg /var/log/apt \
  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  /var/lib/dpkg/updates /var/lib/dpkg/info /var/lib/dpkg/alternatives /etc/dpkg/dpkg.cfg.d /etc/alternatives

# Ports, Custom Apache Logs & Supress Apache Server Name Error
RUN echo 'LogFormat "%{%a %b %d %H:%M:%S %Y}t %H %m %U" customLog' >> /etc/apache2/apache2.conf  && \
  echo 'ErrorLogFormat "%t %M"' >> /etc/apache2/apache2.conf  && \
  echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf && \
  sed -i "s,80,8081,g" /etc/apache2/ports.conf && \
  sed -i "s,443,8080,g" /etc/apache2/ports.conf && \
  a2enmod ssl
COPY container/000-default.conf /etc/apache2/sites-available/000-default.conf
EXPOSE 8080

# Required Read Only Root File System
RUN sed -i "s,ErrorLog \${APACHE_LOG_DIR}/error.log,ErrorLog /proc/self/fd/1,g" /etc/apache2/apache2.conf  && \
  sed -i "s,CustomLog \${APACHE_LOG_DIR}/other_vhosts_access.log,CustomLog /proc/self/fd/1,g" /etc/apache2/conf-available/other-vhosts-access-log.conf && \
  sed -i "s,/var/run/apache2\$SUFFIX/,/dev/shm/,g" /etc/apache2/envvars  && \
  sed -i "s,/var/run/apache2\$SUFFIX,/dev/shm/apache2\$SUFFIX,g" /etc/apache2/envvars  && \
  sed -i "s,#WSGISocketPrefix /var/run/apache2/,WSGISocketPrefix /dev/shm/apache2/,g" /etc/apache2/mods-available/wsgi.conf

# Non Root User Settings
RUN sed -i "s,USER=www-data,USER=nobody,g" /etc/apache2/envvars && \
  sed -i "s,GROUP=www-data,GROUP=nogroup,g" /etc/apache2/envvars && \
  chown -R 65534:65534 /var/log/apache2/ && \
  chown -R 65534:65534 /var/run/apache2/ && \
  chown -R 65534:65534 /proc/self/fd/1 && \
  sed -i "s,.*/socks.*,,g" /usr/sbin/apachectl
# Rootless Apache2 stopped working after this socks change, undoing usptream change.
# https://salsa.debian.org/apache-team/apache2/-/pipelines/395609
# https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1860285.html
# https://salsa.debian.org/apache-team/apache2/-/commit/41653076a91038f63b6fa4895a5add262f34f051
