# FROM python:3.10-slim
FROM debian:bookworm-slim

RUN echo "deb http://deb.debian.org/debian/ bullseye main" >>  /etc/apt/sources.list
RUN echo "deb-src http://deb.debian.org/debian/ bullseye main" >>  /etc/apt/sources.list

RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && \
	apt-get install -y python3 python3-pip libapache2-mod-wsgi-py3 libmariadb-dev gcc \
	apache2=2.4.54-1~deb11u1 apache2-data=2.4.54-1~deb11u1 apache2-bin=2.4.54-1~deb11u1 apache2-utils=2.4.54-1~deb11u1 --allow-downgrades && \
	apt-get autoremove -y && apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Setup Python
COPY requirements.txt /tmp/
RUN pip3 install -r /tmp/requirements.txt
