# FROM python3.10-slim
FROM debian:sid-slim

RUN apt-get update && apt-get install -y python3 python3-pip apache2 libapache2-mod-wsgi-py3 libmariadb-dev gcc && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Setup Python
COPY requirements.txt /tmp/
RUN pip3 install -r /tmp/requirements.txt
