apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-push
  namespace: analytics-for-spotify-ci
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-name
      value: $(body.repository.full_name)
    - name: git-commit
      value: $(body.head_commit.id)
    - name: git-ref
      value: $(body.ref)
