kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-r
  namespace: analytics-for-spotify
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rb
  namespace: analytics-for-spotify
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-r
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: analytics-for-spotify
