kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el
  namespace: analytics-for-spotify-ci
  labels:
    app: analytics-for-spotify
spec:
  to:
    kind: Service
    name: el-webhook
    weight: 100
  port:
    targetPort: 8080
