apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
  namespace: analytics-for-spotify
spec:
  params:
    - name: git-url
    - name: git-name
    - name: git-commit
    - name: git-ref
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "analytics-for-spotify-"
      spec:
        serviceAccountName: pipeline-sa
        timeout: 15m0s
        pipelineRef:
          name: analytics-for-spotify
        workspaces:
          - name: data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 100Mi
                storageClassName: longhorn
                volumeMode: Filesystem
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-name
            value: $(tt.params.git-name)
          - name: git-commit
            value: $(tt.params.git-commit)
          - name: git-ref
            value: $(tt.params.git-ref)
          - name: IMAGE
            value: registry.<path:secret/data/homelab/domain#url>/apps/analytics-for-spotify:$(tt.params.git-commit)
