FROM python:3.9-slim

RUN apt-get update && apt-get install -y libmariadb-dev gcc && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Setup Python
COPY requirements.txt /tmp/
RUN python -m pip install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt
