FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y libmariadb-dev gcc

# Setup Python
COPY requirements.txt /tmp/
RUN python -m pip install --upgrade pip
RUN pip3 install -r /tmp/requirements.txt
