# rm docker-compose.yaml && nano docker-compose.yaml
# docker-compose down
# docker-compose pull
# docker-compose --compatibility up --detach  --remove-orphans
version: "3.7"

services:
  analytics-for-spotify:
    container_name: analytics-for-spotify
    hostname: analytics-for-spotify
    ports:
      - "8080:8080"
    env_file: .env
    image: ${REPOSITORY}
    environment:
        - DOCKER=YES
        - CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
        - REDIRECT_URL=${REDIRECT_URL}
        - DB_HOST=${DB_HOST}
        - DATABASE=${DATABASE}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
