apiVersion: v1
kind: LimitRange
metadata:
  name: default
  namespace: analytics-for-spotify-ci
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 192Mi
        ephemeral-storage: 256Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 128Mi
