apiVersion: generators.external-secrets.io/v1alpha1
kind: QuayAccessToken
metadata:
  name: apps-push-pull-secret
  namespace: analytics-for-spotify-ci
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  url: registry.arthurvardevanyan.com
  robotAccount: apps+push
  serviceAccountRef:
    name: "pipeline"
    audiences:
      - openshift
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apps-push-pull-secret
  namespace: analytics-for-spotify-ci
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: QuayAccessToken
          name: apps-push-pull-secret
  refreshInterval: "55m" # Overlap with Token Expire
  target:
    name: apps-push-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "auth": "{{ .auth }}"
              }
            }
          }
