apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: analytics-for-spotify-token-reviews
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: analytics-for-spotify-ci
  - kind: ServiceAccount
    name: pipeline
    namespace: analytics-for-spotify
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-admin
  namespace: analytics-for-spotify
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: analytics-for-spotify-ci
  - kind: ServiceAccount
    name: pipeline
    namespace: analytics-for-spotify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: analytics-for-spotify-ci
secrets:
  - name: apps-push-pull-secret
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: analytics-for-spotify
  annotations:
    kfca_1: '{ "issuer": "https://storage.googleapis.com/okd-homelab-wif-oidc", "subject": "system:serviceaccount:analytics-for-spotify-ci:pipeline"}'
