apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-cr
  labels:
    app.kubernetes.io/instance: pipeline
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
      - privileged
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clusterinterceptors
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: analytics-for-spotify-crb
  labels:
    app.kubernetes.io/instance: analytics-for-spotify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-cr
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: analytics-for-spotify
