apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-test
  namespace: analytics-for-spotify-ci
spec:
  workspaces:
    - name: data

  sidecars:
    - image: docker.io/library/postgres:18.1@sha256:e9d55eb89617d76161da674975912372a787d16e1945f750fb451d5b8c61242c
      name: postgres
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        privileged: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - MKNOD
            - ALL
      resources:
        requests:
          memory: 192Mi
          cpu: 100m
        limits:
          memory: 384Mi
          cpu: 300m
      ports:
        - containerPort: 3306
      env:
        - name: POSTGRES_USER
          value: spotify
        - name: POSTGRES_PASSWORD
          value: spotify
        - name: POSTGRES_DB
          value: spotify
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: psql
          mountPath: /var/lib/postgresql/data
        - name: tmp
          mountPath: /tmp
        - name: run-psql
          mountPath: "/var/run/postgresql"
  steps:
    - name: unit-test
      image: "registry.arthurvardevanyan.com/apps/analytics-for-spotify:base-builder"
      resources:
        requests:
          memory: 192Mi
          cpu: 100m
        limits:
          memory: 384Mi
          cpu: 300m
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        privileged: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        # seccompProfile:
        #   type: RuntimeDefault
        capabilities:
          drop:
            - MKNOD
            - ALL
      env:
        - name: WORKSPACE_DATA_PATH
          value: $(workspaces.data.path)
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DATABASE
          value: spotify
        - name: DB_USER
          value: spotify #root
        - name: DB_PASSWORD
          value: spotify
        - name: TEST
          value: test
      volumeMounts:
        - name: cache
          mountPath: /.cache/
          subPath: .cache
        - name: cache
          mountPath: /.local/
          subPath: .local
      script: |
        #!/bin/bash

        set -o errexit
        set -o nounset
        set -o pipefail

        retry() {
          local MAX_TRIES
          local DELAY=0
          local ADD_DELAY=30
          MAX_TRIES="${1}"

          shift 1
          for i in $(seq 0 "${MAX_TRIES}"); do
            if [[ "${i}" -eq "${MAX_TRIES}" ]]; then
              break
            fi
            { "${@}" && return 0; } || true
            echo "Failed, retrying...($((i + 1)) of ${MAX_TRIES})"
            DELAY=$((DELAY + ADD_DELAY))
            echo "$(date -u --rfc-3339=seconds) - Waiting ${DELAY} seconds... "
            sleep "${DELAY}"
          done
          local CMD="'$*'"
          echo "Command $CMD failed."
          false
        }


        echo "Waiting for Database to Start"
        cd $(workspaces.data.path)

        python3 -m pip install -r requirements.txt --break-system-packages
        # Install coverage only for CI
        python3 -m pip install coverage --break-system-packages

        # Wait for PostgreSQL to be ready
        echo "Checking database connection..."
        for i in {1..30}; do
          if python3 -c "import psycopg; psycopg.connect('host=127.0.0.1 dbname=spotify user=spotify password=spotify')" 2>/dev/null; then
            echo "Database is ready!"
            break
          fi
          echo "Attempt $i: Database not ready yet, waiting..."
          sleep 2
        done

        test() {
          python3 -m coverage run --source='./monitoringBackend,./webBackend'  manage.py test
          python3 -m coverage report -m
        }
        retry 5 test
  volumes:
    - name: psql
      emptyDir:
        sizeLimit: 200Mi
    - name: tmp
      emptyDir:
        sizeLimit: 1Mi
    - name: run-psql
      emptyDir:
        sizeLimit: 1Mi
    - name: cache
      persistentVolumeClaim:
        claimName: cache
