apiVersion: v1
kind: LimitRange
metadata:
  name: analytics-for-spotify
  namespace: analytics-for-spotify
  labels:
spec:
  limits:
    - default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 50m
        memory: 50Mi
      type: Container
