apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rb
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: analytics-for-spotify
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify
