apiVersion: containerregistry.arthurvardevanyan.com/v1beta1
kind: Auth
metadata:
  name: apps-push-pull-secret
  namespace: analytics-for-spotify
spec:
  serviceAccount: pipeline
  secretName: apps-push-pull-secret
  containerRegistry: quay
  audiences:
    - openshift
  quay:
    robotAccount: "apps+push"
    url: registry.arthurvardevanyan.com
