apiVersion: v1
kind: ResourceQuota
metadata:
  name: analytics-for-spotify
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: "500M"
    limits.cpu: "500m"
    limits.memory: "1000M"
    services.nodeports: "0"
    services.loadbalancers: "0"
    requests.storage: "0"
    requests.ephemeral-storage: "0"
    limits.ephemeral-storage: "0"
