apiVersion: v1
kind: ResourceQuota
metadata:
  name: analytics-for-spotify
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify_analytics-for-spotify
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "5Gi"
    limits.cpu: "5"
    limits.memory: "10Gi"
    services.nodeports: "0"
    services.loadbalancers: "0"
    requests.ephemeral-storage: "0"
    limits.ephemeral-storage: "0"
    local-path.storageclass.storage.k8s.io/requests.storage: "0"
