apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: analytics-for-spotify-cert
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify_analytics-for-spotify
spec:
  secretName: analytics-for-spotify-cert
  dnsNames:
    #- "analytics-for-spotify.apps.okd.arthurvardevanyan.com"
    - "spotify.arthurvardevanyan.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
