apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: spotify.arthurvardevanyan.com
  namespace: analytics-for-spotify
  labels:
    app.kubernetes.io/instance: analytics-for-spotify_analytics-for-spotify
spec:
  ref:
    name: analytics-for-spotify
    kind: Service
    apiVersion: serving.knative.dev/v1
  tls:
    secretName: analytics-for-spotify-cert
# ---
# apiVersion: networking.internal.knative.dev/v1alpha1
# kind: ClusterDomainClaim
# metadata:
#   name: spotify.arthurvardevanyan.com
# spec:
#   namespace: analytics-for-spotify
