# Generated by Django 4.1.2 on 2023-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='artists',
            field=models.ManyToManyField(to='webBackend.artists'),
        ),
        migrations.DeleteModel(
            name='SongArtists',
        ),
    ]
