apiVersion: v1
kind: LimitRange
metadata:
  name: analytics-for-spotify
  namespace: analytics-for-spotify
spec:
  limits:
    - default:
        cpu: 200m
        memory: 250M
      defaultRequest:
        cpu: 100m
        memory: 200M
      type: Container
