apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: analytics-for-spotify
  labels:
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: analytics-for-spotify
  namespace: analytics-for-spotify
  labels:
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: "Host(`spotify.<path:secret/data/homelab/domain#url>`)"
      kind: Rule
      services:
        - name: analytics-for-spotify
          port: 8080
      middlewares:
        - name: https-redirect
  tls:
    domains:
      - main: spotify.<path:secret/data/homelab/domain#url>
